// Code generated by hertz generator.

package main

import (
	"context"
	"io"
	"os"

	"github.com/buyandship/bns-golib/log"
	"github.com/buyandship/bns-golib/log/rollwriter"
	"github.com/buyandship/supply-svr/biz/common/config"
	"github.com/buyandship/supply-svr/biz/infrasturcture/db"
	"github.com/buyandship/supply-svr/biz/infrasturcture/mercari"
	"github.com/buyandship/supply-svr/biz/infrasturcture/redis"
	"github.com/cloudwego/hertz/pkg/app/server"
	cc "github.com/cloudwego/hertz/pkg/common/config"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/hertz-contrib/obs-opentelemetry/provider"
	hertztracing "github.com/hertz-contrib/obs-opentelemetry/tracing"
	"go.opentelemetry.io/otel/propagation"
)

func Init() {
	// Load config
	if err := config.LoadGlobalConfig("./config.yaml"); err != nil {
		hlog.Fatal(err)
	}
	// Connect Mysql
	db.GetHandler()
	// Connect Redis
	redis.GetHandler()
	// Get mercari setting
	mercari.GetHandler()
}

func main() {
	// Load config
	if err := config.LoadGlobalConfig("./config.yaml"); err != nil {
		hlog.Fatal(err)
	}

	Init()
	p := provider.NewOpenTelemetryProvider(
		provider.WithServiceName("supply-svr"),
		provider.WithExportEndpoint(config.GlobalServerConfig.Otel.Endpoint),
		provider.WithInsecure(),
		provider.WithEnableMetrics(false),
	)
	defer p.Shutdown(context.Background())

	// set hlog
	hlog.SetLogger(log.NewHertzZapLogger())
	w2, err := rollwriter.NewRollWriter("logs/supplysrv-app.log",
		rollwriter.WithMaxSize(100), rollwriter.WithMaxBackups(10))
	if err != nil {
		hlog.Fatalf("%s", err.Error())
	}
	multiWriter := io.MultiWriter(os.Stdout, w2)

	hlog.SetOutput(multiWriter)
	hlog.SetLevel(hlog.Level(2))

	propagator := propagation.NewCompositeTextMapPropagator()

	var opts []cc.Option
	tracer, cfg := hertztracing.NewServerTracer(
		hertztracing.WithTextMapPropagator(propagator),
	)
	opts = append(opts, server.WithHostPorts(":8573"))
	opts = append(opts, tracer)

	h := server.Default(opts...)

	h.Use(hertztracing.ServerMiddleware(cfg))
	register(h)
	h.Spin()
}
