// Code generated by hertz generator.

package main

import (
	handler "github.com/buyandship/supply-svr/biz/handler"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/live", handler.HealthCheck)

	// your code ...
}
