// Code generated by hertz generator.

package supply

import (
	"github.com/buyandship/supply-svr/biz/middleware"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mercariMw() []app.HandlerFunc {
	// your code...
	var opt []app.HandlerFunc
	opt = append(opt, middleware.HmacValidator())

	return opt
}

func _mercarigetcategoriesserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mercarigetitemserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mercaripostmessageserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mercaripostorderserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mercarigetsellerserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mercariregisteraccountserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _xbMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mercarilogincallbackserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mercarigettokenserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	// add request id
	var opt []app.HandlerFunc
	opt = append(opt, middleware.RequestIDValidator())
	return opt
}

func _supplysrvMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mercarigettransactionbyitemidserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _internalMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mercari0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mercariposttransactionreviewserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mercarigettodolistserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mercarisearchitemsserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mercarigetbrandsserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _accountMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mercarigetaccountserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publicMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mercarimanualswitchaccountserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _keeptokenaliveserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mercarifetchitemsserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mercarigetsimilaritemsserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _yahooMw() []app.HandlerFunc {
	// your code...
	// TODO: add authentication middleware
	var opt []app.HandlerFunc
	opt = append(opt, middleware.HmacValidator())
	return opt
}

func _yahoobuyoutserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _yahooplacebidserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _yahoogettransactionserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _yahoogetauctionitemserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _yahoogetauctionitemauthserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _yahoogettransactionsserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _transactionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _yahoogetcategorytreeserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _yahoosearchauctionsserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _yahoogetcategoryleafserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _yahoogetmywonlistserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _yahoogetsellinglistserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}
