// Code generated by hertz generator.

package supply

import (
	"github.com/buyandship/supply-svr/biz/middleware"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mercariMw() []app.HandlerFunc {
	// your code...
	var opt []app.HandlerFunc
	opt = append(opt, middleware.HmacValidator())

	return opt
}

func _mercarigetcategoriesserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mercarigetitemserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mercaripostmessageserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mercaripostorderserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mercarigetsellerserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mercariregisteraccountserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _xbMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mercarilogincallbackserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mercarigettokenserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _supplysrvMw() []app.HandlerFunc {
	// your code...
	return nil
}
