CREATE TABLE `mercari`.`account` (
    `id` bigint unsigned NOT NULL AUTO_INCREMENT,
    `created_at` datetime(3) DEFAULT NULL,
    `updated_at` datetime(3) DEFAULT NULL,
    `deleted_at` datetime(3) DEFAULT NULL,
    `email` varchar(255) DEFAULT NULL,
    `buyer_id` varchar(255) DEFAULT NULL,
    `family_name`         varchar(255) DEFAULT NULL,
    `family_name_kana` varchar(255) DEFAULT NULL,
    `first_name` varchar(255) DEFAULT NULL,
    `first_name_kana` varchar(255) DEFAULT NULL,
    `telephone` varchar(255) DEFAULT NULL,
    `zipcode1` varchar(255) DEFAULT NULL,
    `zipcode2` varchar(255) DEFAULT NULL,
    `prefecture` varchar(255) DEFAULT NULL,
    `city` varchar(255) DEFAULT NULL,
    `address1` varchar(255) DEFAULT NULL,
    `address2` varchar(255) DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_buyer_id` (`buyer_id`),
    KEY `idx_deleted_at` (`deleted_at`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci