// Code generated by hertz generator.

package supply

import (
	"context"
	bizErr "github.com/buyandship/supply-svr/biz/common/err"
	"github.com/buyandship/supply-svr/biz/handler/bns/supply/mercari"
	"github.com/buyandship/supply-svr/biz/model/bns/supply"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// MercariGetItemService .
// @router /mercari/item [GET]
func MercariGetItemService(ctx context.Context, c *app.RequestContext) {
	var err error
	var req supply.MercariGetItemReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.AbortWithStatusJSON(consts.StatusBadRequest, bizErr.InvalidParameterError)
		return
	}
	resp, err := mercari.GetItemService(ctx, &req)
	if err != nil {
		cerr := bizErr.ConvertErr(err)
		c.AbortWithStatusJSON(cerr.Status, cerr)
	}
	c.JSON(consts.StatusOK, resp)
}

// MercariGetCategoriesService .
// @router /mercari/categories [GET]
func MercariGetCategoriesService(ctx context.Context, c *app.RequestContext) {
	var err error
	var req supply.MercariGetCategoriesReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.AbortWithStatusJSON(consts.StatusBadRequest, bizErr.InvalidParameterError)
		return
	}

	resp, err := mercari.GetCategoriesService(ctx, &req)
	if err != nil {
		cerr := bizErr.ConvertErr(err)
		c.AbortWithStatusJSON(cerr.Status, cerr)
	}
	c.JSON(consts.StatusOK, resp)
}

// MercariGetSellerService .
// @router /mercari/seller [GET]
func MercariGetSellerService(ctx context.Context, c *app.RequestContext) {
	var err error
	var req supply.MercariGetSellerReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.AbortWithStatusJSON(consts.StatusBadRequest, bizErr.InvalidParameterError)
		return
	}
	resp, err := mercari.GetSellerService(ctx, &req)
	if err != nil {
		cerr := bizErr.ConvertErr(err)
		c.AbortWithStatusJSON(cerr.Status, cerr)
	}
	c.JSON(consts.StatusOK, resp)
}

// MercariPostOrderService .
// @router /mercari/order [POST]
func MercariPostOrderService(ctx context.Context, c *app.RequestContext) {
	var err error
	var req supply.MercariPostOrderReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.AbortWithStatusJSON(consts.StatusBadRequest, bizErr.InvalidParameterError)
		return
	}
	resp, err := mercari.PostOrderService(ctx, &req)
	if err != nil {
		cerr := bizErr.ConvertErr(err)
		c.AbortWithStatusJSON(cerr.Status, cerr)
	}
	c.JSON(consts.StatusOK, resp)
}

// MercariPostMessageService .
// @router /mercari/message [POST]
func MercariPostMessageService(ctx context.Context, c *app.RequestContext) {
	var err error
	var req supply.MercariPostMessageReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.AbortWithStatusJSON(consts.StatusBadRequest, bizErr.InvalidParameterError)
		return
	}
	resp, err := mercari.PostMessageService(ctx, &req)
	if err != nil {
		cerr := bizErr.ConvertErr(err)
		c.AbortWithStatusJSON(cerr.Status, cerr)
	}
	c.JSON(consts.StatusOK, resp)
}

// MercariRegisterAccountService .
// @router /mercari/register [POST]
func MercariRegisterAccountService(ctx context.Context, c *app.RequestContext) {
	var err error
	var req supply.MercariRegisterAccountReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := mercari.RegisterAccountService(ctx, &req)
	if err != nil {
		cerr := bizErr.ConvertErr(err)
		c.AbortWithStatusJSON(cerr.Status, cerr)
	}
	c.JSON(consts.StatusOK, resp)
}
