// Code generated by hertz generator.

package supply

import (
	"context"

	bizErr "github.com/buyandship/supply-svr/biz/common/err"
	"github.com/buyandship/supply-svr/biz/handler/bns/supply/mercari"
	"github.com/buyandship/supply-svr/biz/model/bns/supply"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/google/uuid"
	hertzzap "github.com/hertz-contrib/logger/zap"
)

// MercariGetItemService .
// @router /mercari/item [GET]
func MercariGetItemService(ctx context.Context, c *app.RequestContext) {
	var requestId string
	if string(c.GetHeader("X-Request-ID")) == "" {
		requestId = uuid.NewString()
	} else {
		requestId = string(c.GetHeader("X-Request-ID"))
	}
	ctx = context.WithValue(ctx, hertzzap.ExtraKey("X-Request-ID"), requestId)

	var err error
	var req supply.MercariGetItemReq
	err = c.BindAndValidate(&req)
	if err != nil {
		hlog.CtxErrorf(ctx, "invalid parameter, err: %+v", err)
		c.AbortWithStatusJSON(consts.StatusBadRequest, bizErr.InvalidParameterError)
		return
	}

	resp, err := mercari.GetItemService(ctx, &req)
	if err != nil {
		cerr := bizErr.ConvertErr(err)
		c.AbortWithStatusJSON(cerr.Status, cerr)
		return
	}
	c.JSON(consts.StatusOK, resp)
}

// MercariGetCategoriesService .
// @router /mercari/categories [GET]
func MercariGetCategoriesService(ctx context.Context, c *app.RequestContext) {
	var requestId string
	if string(c.GetHeader("X-Request-ID")) == "" {
		requestId = uuid.NewString()
	} else {
		requestId = string(c.GetHeader("X-Request-ID"))
	}
	ctx = context.WithValue(ctx, hertzzap.ExtraKey("X-Request-ID"), requestId)

	resp, err := mercari.GetCategoriesService(ctx)
	if err != nil {
		cerr := bizErr.ConvertErr(err)
		c.AbortWithStatusJSON(cerr.Status, cerr)
		return
	}
	c.JSON(consts.StatusOK, resp)
}

// MercariGetSellerService .
// @router /mercari/seller [GET]
func MercariGetSellerService(ctx context.Context, c *app.RequestContext) {
	var requestId string
	if string(c.GetHeader("X-Request-ID")) == "" {
		requestId = uuid.NewString()
	} else {
		requestId = string(c.GetHeader("X-Request-ID"))
	}
	ctx = context.WithValue(ctx, hertzzap.ExtraKey("X-Request-ID"), requestId)

	var err error
	var req supply.MercariGetSellerReq
	err = c.BindAndValidate(&req)
	if err != nil {
		hlog.CtxErrorf(ctx, "invalid parameter, err: %+v", err)
		c.AbortWithStatusJSON(consts.StatusBadRequest, bizErr.InvalidParameterError)
		return
	}

	resp, err := mercari.GetSellerService(ctx, &req)
	if err != nil {
		cerr := bizErr.ConvertErr(err)
		c.AbortWithStatusJSON(cerr.Status, cerr)
		return
	}
	c.JSON(consts.StatusOK, resp)
}

// MercariPostOrderService .
// @router /mercari/order [POST]
func MercariPostOrderService(ctx context.Context, c *app.RequestContext) {
	var requestId string
	if string(c.GetHeader("X-Request-ID")) == "" {
		requestId = uuid.NewString()
	} else {
		requestId = string(c.GetHeader("X-Request-ID"))
	}
	ctx = context.WithValue(ctx, hertzzap.ExtraKey("X-Request-ID"), requestId)

	var err error
	var req supply.MercariPostOrderReq
	err = c.BindAndValidate(&req)
	if err != nil {
		hlog.CtxErrorf(ctx, "invalid parameter, err: %+v", err)
		c.AbortWithStatusJSON(consts.StatusBadRequest, bizErr.InvalidParameterError)
		return
	}
	resp, err := mercari.PostOrderService(ctx, &req)
	if err != nil {
		cerr := bizErr.ConvertErr(err)
		c.AbortWithStatusJSON(cerr.Status, cerr)
		return
	}
	c.JSON(consts.StatusOK, resp)
}

// MercariPostMessageService .
// @router /mercari/message [POST]
func MercariPostMessageService(ctx context.Context, c *app.RequestContext) {
	var requestId string
	if string(c.GetHeader("X-Request-ID")) == "" {
		requestId = uuid.NewString()
	} else {
		requestId = string(c.GetHeader("X-Request-ID"))
	}
	ctx = context.WithValue(ctx, hertzzap.ExtraKey("X-Request-ID"), requestId)

	var err error
	var req supply.MercariPostMessageReq
	err = c.BindAndValidate(&req)
	if err != nil {
		hlog.CtxErrorf(ctx, "invalid parameter, err: %+v", err)
		c.AbortWithStatusJSON(consts.StatusBadRequest, bizErr.InvalidParameterError)
		return
	}
	resp, err := mercari.PostMessageService(ctx, &req)
	if err != nil {
		cerr := bizErr.ConvertErr(err)
		c.AbortWithStatusJSON(cerr.Status, cerr)
		return
	}
	c.JSON(consts.StatusOK, resp)
}

// MercariRegisterAccountService .
// @router /mercari/register [POST]
func MercariRegisterAccountService(ctx context.Context, c *app.RequestContext) {
	var requestId string
	if string(c.GetHeader("X-Request-ID")) == "" {
		requestId = uuid.NewString()
	} else {
		requestId = string(c.GetHeader("X-Request-ID"))
	}
	ctx = context.WithValue(ctx, hertzzap.ExtraKey("X-Request-ID"), requestId)

	var err error
	var req supply.MercariRegisterAccountReq
	err = c.BindAndValidate(&req)
	if err != nil {
		hlog.CtxErrorf(ctx, "invalid parameter, err: %+v", err)
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := mercari.RegisterAccountService(ctx, &req)
	if err != nil {
		cerr := bizErr.ConvertErr(err)
		c.AbortWithStatusJSON(cerr.Status, cerr)
		return
	}
	c.JSON(consts.StatusOK, resp)
}

// MercariLoginCallBackService .
// @router /xb/login_callback [POST]
func MercariLoginCallBackService(ctx context.Context, c *app.RequestContext) {
	var requestId string
	if string(c.GetHeader("X-Request-ID")) == "" {
		requestId = uuid.NewString()
	} else {
		requestId = string(c.GetHeader("X-Request-ID"))
	}
	ctx = context.WithValue(ctx, hertzzap.ExtraKey("X-Request-ID"), requestId)

	var err error
	var req supply.MercariLoginCallBackReq
	err = c.BindAndValidate(&req)
	if err != nil {
		hlog.CtxErrorf(ctx, "invalid parameter, err: %+v", err)
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	req.RedirectUrl = c.URI().String()

	if err := mercari.LoginCallBackService(ctx, &req); err != nil {
		cerr := bizErr.ConvertErr(err)
		c.AbortWithStatusJSON(cerr.Status, cerr)
		return
	}
	c.JSON(consts.StatusOK, "success")
}

// MercariGetTokenService .
// @router /mercari/token [GET]
func MercariGetTokenService(ctx context.Context, c *app.RequestContext) {
	var err error

	var requestId string
	if string(c.GetHeader("X-Request-ID")) == "" {
		requestId = uuid.NewString()
	} else {
		requestId = string(c.GetHeader("X-Request-ID"))
	}
	ctx = context.WithValue(ctx, hertzzap.ExtraKey("X-Request-ID"), requestId)

	resp, err := mercari.GetTokenService(ctx)
	if err != nil {
		cerr := bizErr.ConvertErr(err)
		c.AbortWithStatusJSON(cerr.Status, cerr)
		return
	}
	c.JSON(consts.StatusOK, resp)
}

// MercariGetTransactionByItemIdService .
// @router /v1/supplysrv/mercari/tx [GET]
func MercariGetTransactionByItemIdService(ctx context.Context, c *app.RequestContext) {
	var requestId string
	if string(c.GetHeader("X-Request-ID")) == "" {
		requestId = uuid.NewString()
	} else {
		requestId = string(c.GetHeader("X-Request-ID"))
	}
	ctx = context.WithValue(ctx, hertzzap.ExtraKey("X-Request-ID"), requestId)

	var err error
	var req supply.MercariGetTransactionByItemIdReq
	err = c.BindAndValidate(&req)
	if err != nil {
		hlog.CtxErrorf(ctx, "invalid parameter, err: %+v", err)
		c.AbortWithStatusJSON(consts.StatusBadRequest, bizErr.InvalidParameterError)
		return
	}

	resp, err := mercari.GetTransactionByItemIdService(ctx, &req)
	if err != nil {
		cerr := bizErr.ConvertErr(err)
		c.AbortWithStatusJSON(cerr.Status, cerr)
		return
	}
	c.JSON(consts.StatusOK, resp)
}

// MercariPostTransactionReviewService .
// @router /v1/supplysrv/internal/mercari/review [GET]
func MercariPostTransactionReviewService(ctx context.Context, c *app.RequestContext) {
	var requestId string
	if string(c.GetHeader("X-Request-ID")) == "" {
		requestId = uuid.NewString()
	} else {
		requestId = string(c.GetHeader("X-Request-ID"))
	}
	ctx = context.WithValue(ctx, hertzzap.ExtraKey("X-Request-ID"), requestId)

	var err error
	var req supply.MercariPostTransactionReviewReq
	err = c.BindAndValidate(&req)
	if err != nil {
		hlog.CtxErrorf(ctx, "invalid parameter, err: %+v", err)
		c.AbortWithStatusJSON(consts.StatusBadRequest, bizErr.InvalidParameterError)
		return
	}
	resp, err := mercari.PostTransactionReviewService(ctx, &req)
	if err != nil {
		cerr := bizErr.ConvertErr(err)
		c.AbortWithStatusJSON(cerr.Status, cerr)
		return
	}
	c.JSON(consts.StatusOK, resp)
}

// MercariGetTodoListService .
// @router /v1/supplysrv/internal/mercari/todo [GET]
func MercariGetTodoListService(ctx context.Context, c *app.RequestContext) {
	var requestId string
	if string(c.GetHeader("X-Request-ID")) == "" {
		requestId = uuid.NewString()
	} else {
		requestId = string(c.GetHeader("X-Request-ID"))
	}
	ctx = context.WithValue(ctx, hertzzap.ExtraKey("X-Request-ID"), requestId)

	var err error
	var req supply.MercariGetTodoListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := mercari.GetTodoListService(ctx, &req)
	if err != nil {
		cerr := bizErr.ConvertErr(err)
		c.AbortWithStatusJSON(cerr.Status, cerr)
		return
	}
	c.JSON(consts.StatusOK, resp)
}
