// Code generated by hertz generator.

package handler

import (
	"context"
	"github.com/buyandship/supply-svr/biz/infrasturcture/db"
	"github.com/buyandship/supply-svr/biz/infrasturcture/redis"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// HealthCheck .
func HealthCheck(ctx context.Context, c *app.RequestContext) {

	if err := db.Handler.HealthCheck(); err != nil {
		// TODO
	}

	if err := redis.Handler.HealthCheck(); err != nil {
		// TODO
	}

	c.JSON(consts.StatusOK, utils.H{
		"message": "pong",
	})
}
