// Code generated by hertz generator.

package handler

import (
	"context"
	"net/http"

	"github.com/buyandship/bns-golib/cache"
	"github.com/buyandship/supply-service/biz/infrasturcture/db"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// HealthCheck .
func HealthCheck(ctx context.Context, c *app.RequestContext) {
	if err := db.Handler.HealthCheck(); err != nil {
		c.AbortWithStatusJSON(http.StatusInternalServerError, "can not connect to db.")
		return
	}
	if err := cache.GetRedisClient().HealthCheck(); err != nil {
		c.AbortWithStatusJSON(http.StatusInternalServerError, "can not connect to redis.")
		return
	}
	c.JSON(consts.StatusOK, "ok")
}
