// Code generated by Validator v0.2.3. DO NOT EDIT.

package supply

import (
	"bytes"
	"fmt"
	"reflect"
	"regexp"
	"strings"
	"time"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = (*regexp.Regexp)(nil)
	_ = time.Nanosecond
)

func (p *MercariGetItemReq) IsValid() error {
	return nil
}
func (p *MercariGetSellerReq) IsValid() error {
	return nil
}
func (p *MercariPostOrderReq) IsValid() error {
	return nil
}
func (p *MercariPostMessageReq) IsValid() error {
	return nil
}
func (p *MercariPostMessageResp) IsValid() error {
	return nil
}
func (p *MercariRegisterAccountReq) IsValid() error {
	return nil
}
func (p *Account) IsValid() error {
	return nil
}
func (p *MercariRegisterAccountResp) IsValid() error {
	if p.Account != nil {
		if err := p.Account.IsValid(); err != nil {
			return fmt.Errorf("field Account not valid, %w", err)
		}
	}
	return nil
}
func (p *MercariLoginCallBackReq) IsValid() error {
	return nil
}
func (p *MercariGetTokenResp) IsValid() error {
	return nil
}
func (p *MercariGetTransactionByItemIdReq) IsValid() error {
	return nil
}
func (p *MercariPostOrderResp) IsValid() error {
	return nil
}
func (p *MercariPostTransactionReviewReq) IsValid() error {
	return nil
}
func (p *MercariGetTodoListReq) IsValid() error {
	return nil
}
func (p *MercariSearchItemsReq) IsValid() error {
	return nil
}
func (p *MercariGetAccountResp) IsValid() error {
	return nil
}
func (p *MercariManualSwitchAccountReq) IsValid() error {
	return nil
}
func (p *MercariFetchItemsReq) IsValid() error {
	return nil
}
func (p *MercariGetSimilarItemsReq) IsValid() error {
	return nil
}
func (p *YahooPlaceBidReq) IsValid() error {
	return nil
}
func (p *YahooPlaceBidResp) IsValid() error {
	return nil
}
func (p *YahooGetTransactionReq) IsValid() error {
	return nil
}
func (p *YahooTransaction) IsValid() error {
	return nil
}
func (p *YahooGetTransactionsResp) IsValid() error {
	return nil
}
func (p *YahooGetAuctionItemReq) IsValid() error {
	if len(p.AuctionID) < int(1) {
		return fmt.Errorf("field AuctionID min_len rule failed, current value: %d", len(p.AuctionID))
	}
	return nil
}
func (p *Seller) IsValid() error {
	return nil
}
func (p *YahooGetAuctionItemResp) IsValid() error {
	if p.Seller != nil {
		if err := p.Seller.IsValid(); err != nil {
			return fmt.Errorf("field Seller not valid, %w", err)
		}
	}
	return nil
}
func (p *YahooGetAuctionItemAuthReq) IsValid() error {
	return nil
}
func (p *BidStatus) IsValid() error {
	return nil
}
func (p *YahooGetAuctionItemAuthResp) IsValid() error {
	if p.AuctionItem != nil {
		if err := p.AuctionItem.IsValid(); err != nil {
			return fmt.Errorf("field AuctionItem not valid, %w", err)
		}
	}
	if p.BidStatus != nil {
		if err := p.BidStatus.IsValid(); err != nil {
			return fmt.Errorf("field BidStatus not valid, %w", err)
		}
	}
	return nil
}
