// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/mercari/categories": {
            "get": {
                "description": "Get list of all available categories from Mercari",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mercari"
                ],
                "summary": "Get Mercari categories",
                "responses": {
                    "200": {
                        "description": "Successfully retrieved categories",
                        "schema": {
                            "$ref": "#/definitions/mercari.GetItemCategoriesResp"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/err.BizError"
                        }
                    }
                }
            }
        },
        "/mercari/item": {
            "get": {
                "description": "Get detailed information about a Mercari item by item ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mercari"
                ],
                "summary": "Get Mercari item details",
                "parameters": [
                    {
                        "type": "string",
                        "name": "item_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved item information",
                        "schema": {
                            "$ref": "#/definitions/mercari.GetItemByIDResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid parameter",
                        "schema": {
                            "$ref": "#/definitions/err.BizError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/err.BizError"
                        }
                    }
                }
            }
        },
        "/mercari/message": {
            "post": {
                "description": "Send a message to a seller or buyer on Mercari marketplace",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mercari"
                ],
                "summary": "Send Mercari message",
                "parameters": [
                    {
                        "description": "Message request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/supply.MercariPostMessageReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Message sent successfully",
                        "schema": {
                            "$ref": "#/definitions/supply.MercariPostMessageResp"
                        }
                    },
                    "400": {
                        "description": "Invalid parameter",
                        "schema": {
                            "$ref": "#/definitions/err.BizError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/err.BizError"
                        }
                    }
                }
            }
        },
        "/mercari/order": {
            "post": {
                "description": "Place a new order for items on Mercari marketplace",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mercari"
                ],
                "summary": "Create Mercari order",
                "parameters": [
                    {
                        "description": "Order request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/supply.MercariPostOrderReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Order created successfully",
                        "schema": {
                            "$ref": "#/definitions/supply.MercariPostOrderResp"
                        }
                    },
                    "400": {
                        "description": "Invalid parameter",
                        "schema": {
                            "$ref": "#/definitions/err.BizError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/err.BizError"
                        }
                    }
                }
            }
        },
        "/mercari/register": {
            "post": {
                "description": "Register a new Mercari account for API access",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mercari"
                ],
                "summary": "Register Mercari account",
                "parameters": [
                    {
                        "description": "Account registration request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/supply.MercariRegisterAccountReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Account registered successfully",
                        "schema": {
                            "$ref": "#/definitions/supply.MercariRegisterAccountResp"
                        }
                    },
                    "400": {
                        "description": "Invalid parameter",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/err.BizError"
                        }
                    }
                }
            }
        },
        "/mercari/seller": {
            "get": {
                "description": "Get detailed information about a Mercari seller by seller ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mercari"
                ],
                "summary": "Get Mercari seller details",
                "parameters": [
                    {
                        "type": "string",
                        "name": "seller_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved seller information",
                        "schema": {
                            "$ref": "#/definitions/mercari.GetUserByUserIDResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid parameter",
                        "schema": {
                            "$ref": "#/definitions/err.BizError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/err.BizError"
                        }
                    }
                }
            }
        },
        "/mercari/token": {
            "get": {
                "description": "Get access token for Mercari API authentication",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mercari"
                ],
                "summary": "Get Mercari token",
                "responses": {
                    "200": {
                        "description": "Successfully retrieved token",
                        "schema": {
                            "$ref": "#/definitions/supply.MercariGetTokenResp"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/err.BizError"
                        }
                    }
                }
            }
        },
        "/v1/supplysrv/internal/mercari/account/list": {
            "get": {
                "description": "Get list of all registered Mercari accounts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mercari"
                ],
                "summary": "Get Mercari account list",
                "responses": {
                    "200": {
                        "description": "Successfully retrieved account list",
                        "schema": {
                            "$ref": "#/definitions/supply.MercariGetAccountResp"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/err.BizError"
                        }
                    }
                }
            }
        },
        "/v1/supplysrv/internal/mercari/brands": {
            "get": {
                "description": "Get list of all available brands from Mercari",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mercari"
                ],
                "summary": "Get Mercari brands",
                "responses": {
                    "200": {
                        "description": "Successfully retrieved brands",
                        "schema": {
                            "$ref": "#/definitions/mercari.GetBrandsResp"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/err.BizError"
                        }
                    }
                }
            }
        },
        "/v1/supplysrv/internal/mercari/fetch_items": {
            "post": {
                "description": "Fetch multiple items from Mercari marketplace by item IDs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mercari"
                ],
                "summary": "Fetch Mercari items",
                "parameters": [
                    {
                        "description": "Fetch items request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/supply.MercariFetchItemsReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully fetched items",
                        "schema": {
                            "$ref": "#/definitions/mercari.FetchItemsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid parameter",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/err.BizError"
                        }
                    }
                }
            }
        },
        "/v1/supplysrv/internal/mercari/keep_token_alive": {
            "post": {
                "description": "Refresh and keep the Mercari access token active",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mercari"
                ],
                "summary": "Keep Mercari token alive",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/err.BizError"
                        }
                    }
                }
            }
        },
        "/v1/supplysrv/internal/mercari/review": {
            "get": {
                "description": "Submit a review for a Mercari transaction",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mercari"
                ],
                "summary": "Post Mercari transaction review",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "account_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "fame",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "review",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "trx_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Review submitted successfully",
                        "schema": {
                            "$ref": "#/definitions/mercari.PostTransactionReviewResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid parameter",
                        "schema": {
                            "$ref": "#/definitions/err.BizError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/err.BizError"
                        }
                    }
                }
            }
        },
        "/v1/supplysrv/internal/mercari/search": {
            "get": {
                "description": "Search for items on Mercari marketplace with filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mercari"
                ],
                "summary": "Search Mercari items",
                "parameters": [
                    {
                        "type": "string",
                        "name": "brand_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "category_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "color_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "created_after_date",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "created_before_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "exclude_keyword",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "name": "item_authentication",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "item_condition_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "marketplace",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "price_max",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "price_min",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "seller_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "shipping_payer_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "shop_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "size_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "name": "time_sale",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "name": "with_offer_price_promotion",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved search results",
                        "schema": {
                            "$ref": "#/definitions/mercari.SearchItemsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid parameter",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/err.BizError"
                        }
                    }
                }
            }
        },
        "/v1/supplysrv/internal/mercari/similar_items": {
            "get": {
                "description": "Get list of items similar to a given Mercari item",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mercari"
                ],
                "summary": "Get similar Mercari items",
                "parameters": [
                    {
                        "type": "string",
                        "name": "item_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved similar items",
                        "schema": {
                            "$ref": "#/definitions/mercari.GetSimilarItemsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid parameter",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/err.BizError"
                        }
                    }
                }
            }
        },
        "/v1/supplysrv/internal/mercari/todo": {
            "get": {
                "description": "Get list of pending todo items from Mercari",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mercari"
                ],
                "summary": "Get Mercari todo list",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "page_token",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved todo list",
                        "schema": {
                            "$ref": "#/definitions/mercari.GetTodoListResp"
                        }
                    },
                    "400": {
                        "description": "Invalid parameter",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/err.BizError"
                        }
                    }
                }
            }
        },
        "/v1/supplysrv/internal/yahoo/auctionItem": {
            "get": {
                "description": "Get detailed information about a Yahoo Auction item",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Yahoo"
                ],
                "summary": "Get Yahoo Auction item",
                "parameters": [
                    {
                        "type": "string",
                        "example": "a7062ca18a39e7ec551499958684745f3bd28227c7ae52b5246492c738fa7989",
                        "name": "hmac",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "1762155727995",
                        "name": "timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "adc3d4cb-d4d0-4a74-9908-5b95bee4d62b",
                        "name": "X-Request-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "auction_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved auction item",
                        "schema": {
                            "$ref": "#/definitions/supply.YahooGetAuctionItemResp"
                        }
                    },
                    "400": {
                        "description": "Invalid parameter",
                        "schema": {
                            "$ref": "#/definitions/err.BizError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/err.BizError"
                        }
                    }
                }
            }
        },
        "/v1/supplysrv/internal/yahoo/auctionItemAuth": {
            "get": {
                "description": "Get detailed information about a Yahoo Auction item with user authentication",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Yahoo"
                ],
                "summary": "Get Yahoo Auction item with authentication",
                "parameters": [
                    {
                        "type": "string",
                        "example": "a7062ca18a39e7ec551499958684745f3bd28227c7ae52b5246492c738fa7989",
                        "name": "hmac",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "1762155727995",
                        "name": "timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "adc3d4cb-d4d0-4a74-9908-5b95bee4d62b",
                        "name": "X-Request-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "auction_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved authenticated auction item",
                        "schema": {
                            "$ref": "#/definitions/supply.YahooGetAuctionItemAuthResp"
                        }
                    },
                    "400": {
                        "description": "Invalid parameter",
                        "schema": {
                            "$ref": "#/definitions/err.BizError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/err.BizError"
                        }
                    }
                }
            }
        },
        "/v1/supplysrv/internal/yahoo/placeBid": {
            "post": {
                "description": "Place a bid on an item in Yahoo Auction marketplace",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Yahoo"
                ],
                "summary": "Place bid on Yahoo Auction",
                "parameters": [
                    {
                        "type": "string",
                        "example": "a7062ca18a39e7ec551499958684745f3bd28227c7ae52b5246492c738fa7989",
                        "name": "hmac",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "1762155727995",
                        "name": "timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "adc3d4cb-d4d0-4a74-9908-5b95bee4d62b",
                        "name": "X-Request-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Bid request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/supply.YahooPlaceBidReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Bid placed successfully",
                        "schema": {
                            "$ref": "#/definitions/supply.YahooPlaceBidResp"
                        }
                    },
                    "400": {
                        "description": "Invalid parameter",
                        "schema": {
                            "$ref": "#/definitions/err.BizError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/err.BizError"
                        }
                    }
                }
            }
        },
        "/v1/supplysrv/internal/yahoo/transaction": {
            "get": {
                "description": "Get transaction details from Yahoo Auction",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Yahoo"
                ],
                "summary": "Get Yahoo Auction transaction",
                "parameters": [
                    {
                        "type": "string",
                        "example": "a7062ca18a39e7ec551499958684745f3bd28227c7ae52b5246492c738fa7989",
                        "name": "hmac",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "1762155727995",
                        "name": "timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "adc3d4cb-d4d0-4a74-9908-5b95bee4d62b",
                        "name": "X-Request-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Transaction ID",
                        "name": "transaction_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved transaction",
                        "schema": {
                            "$ref": "#/definitions/supply.YahooTransaction"
                        }
                    },
                    "400": {
                        "description": "Invalid parameter",
                        "schema": {
                            "$ref": "#/definitions/err.BizError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/err.BizError"
                        }
                    }
                }
            }
        },
        "/v1/supplysrv/mercari/tx": {
            "get": {
                "description": "Get transaction information for a specific Mercari item",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mercari"
                ],
                "summary": "Get Mercari transaction by item ID",
                "parameters": [
                    {
                        "type": "string",
                        "name": "item_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved transaction",
                        "schema": {
                            "$ref": "#/definitions/mercari.GetTransactionByItemIDResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid parameter",
                        "schema": {
                            "$ref": "#/definitions/err.BizError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/err.BizError"
                        }
                    }
                }
            }
        },
        "/v1/supplysrv/public/mercari/switch_account": {
            "post": {
                "description": "Manually switch the active Mercari account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mercari"
                ],
                "summary": "Switch Mercari account manually",
                "parameters": [
                    {
                        "description": "Account switch request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/supply.MercariManualSwitchAccountReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid parameter",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/err.BizError"
                        }
                    }
                }
            }
        },
        "/xb/login_callback": {
            "post": {
                "description": "Handle OAuth callback from Mercari login flow",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mercari"
                ],
                "summary": "Mercari login callback",
                "parameters": [
                    {
                        "description": "Login callback request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/supply.MercariLoginCallBackReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid parameter",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/err.BizError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "err.BizError": {
            "type": "object",
            "properties": {
                "errCode": {
                    "type": "integer"
                },
                "errMsg": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "github_com_buyandship_supply-svr_biz_infrasturcture_mercari.AnshinItemAuthentication": {
            "type": "object",
            "properties": {
                "fee": {
                    "type": "integer"
                },
                "is_authenticatable": {
                    "type": "boolean"
                }
            }
        },
        "github_com_buyandship_supply-svr_biz_infrasturcture_mercari.Item": {
            "type": "object",
            "properties": {
                "anshin_item_authentication": {
                    "$ref": "#/definitions/github_com_buyandship_supply-svr_biz_infrasturcture_mercari.AnshinItemAuthentication"
                },
                "created": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "item_brand": {
                    "$ref": "#/definitions/github_com_buyandship_supply-svr_biz_infrasturcture_mercari.ItemBrand"
                },
                "item_category": {
                    "$ref": "#/definitions/github_com_buyandship_supply-svr_biz_infrasturcture_mercari.ItemCategory"
                },
                "item_condition": {
                    "$ref": "#/definitions/github_com_buyandship_supply-svr_biz_infrasturcture_mercari.ItemCondition"
                },
                "item_discount": {
                    "$ref": "#/definitions/mercari.ItemDiscount"
                },
                "item_sizes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_buyandship_supply-svr_biz_infrasturcture_mercari.ItemSize"
                    }
                },
                "item_type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "photos": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "price": {
                    "type": "integer"
                },
                "seller": {
                    "$ref": "#/definitions/github_com_buyandship_supply-svr_biz_infrasturcture_mercari.Seller"
                },
                "shipping_duration": {
                    "$ref": "#/definitions/github_com_buyandship_supply-svr_biz_infrasturcture_mercari.ShippingDuration"
                },
                "shipping_payer": {
                    "$ref": "#/definitions/github_com_buyandship_supply-svr_biz_infrasturcture_mercari.ShippingPayer"
                },
                "status": {
                    "type": "string"
                },
                "thumbnail": {
                    "type": "string"
                },
                "updated": {
                    "type": "integer"
                }
            }
        },
        "github_com_buyandship_supply-svr_biz_infrasturcture_mercari.ItemBrand": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "sub_name": {
                    "type": "string"
                }
            }
        },
        "github_com_buyandship_supply-svr_biz_infrasturcture_mercari.ItemCategory": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_buyandship_supply-svr_biz_infrasturcture_mercari.ItemCondition": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_buyandship_supply-svr_biz_infrasturcture_mercari.ItemSize": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_buyandship_supply-svr_biz_infrasturcture_mercari.Seller": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "rating": {
                    "type": "number"
                },
                "shop_id": {
                    "type": "string"
                }
            }
        },
        "github_com_buyandship_supply-svr_biz_infrasturcture_mercari.ShippingDuration": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "max_days": {
                    "type": "integer"
                },
                "min_days": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_buyandship_supply-svr_biz_infrasturcture_mercari.ShippingPayer": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "mercari.FetchItemsResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/github_com_buyandship_supply-svr_biz_infrasturcture_mercari.Item"
                    }
                }
            }
        },
        "mercari.GetBrandsResp": {
            "type": "object",
            "properties": {
                "master_brands": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "id": {
                                "type": "string"
                            },
                            "name_en": {
                                "type": "string"
                            },
                            "name_ja": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "mercari.GetItemByIDResponse": {
            "type": "object",
            "properties": {
                "anshin_item_authentication": {
                    "type": "object",
                    "properties": {
                        "fee": {
                            "type": "integer"
                        },
                        "is_authenticatable": {
                            "type": "boolean"
                        }
                    }
                },
                "checksum": {
                    "type": "string"
                },
                "created": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "discounts": {
                    "type": "object",
                    "properties": {
                        "breakdown": {
                            "type": "object",
                            "properties": {
                                "inhouse_item_discount": {
                                    "type": "object",
                                    "properties": {
                                        "discount_order": {
                                            "type": "integer"
                                        },
                                        "expire": {
                                            "type": "integer"
                                        },
                                        "return_absolute": {
                                            "type": "integer"
                                        },
                                        "return_percent": {
                                            "type": "integer"
                                        }
                                    }
                                },
                                "item_coupon": {
                                    "type": "object",
                                    "properties": {
                                        "coupon_id": {
                                            "type": "integer"
                                        },
                                        "discount_order": {
                                            "type": "integer"
                                        },
                                        "expire": {
                                            "type": "integer"
                                        },
                                        "return_absolute": {
                                            "type": "integer"
                                        },
                                        "return_percent": {
                                            "type": "integer"
                                        }
                                    }
                                },
                                "offer_to_everyone": {
                                    "type": "object",
                                    "properties": {
                                        "discount_order": {
                                            "type": "integer"
                                        },
                                        "expire": {
                                            "type": "integer"
                                        },
                                        "return_absolute": {
                                            "type": "integer"
                                        },
                                        "return_percent": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            }
                        },
                        "total_return_absolute": {
                            "type": "integer"
                        },
                        "total_return_percent": {
                            "type": "integer"
                        }
                    }
                },
                "id": {
                    "type": "string"
                },
                "item_brand": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "integer"
                        },
                        "name": {
                            "type": "string"
                        },
                        "sub_name": {
                            "type": "string"
                        }
                    }
                },
                "item_category": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "integer"
                        },
                        "name": {
                            "type": "string"
                        }
                    }
                },
                "item_condition": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "integer"
                        },
                        "name": {
                            "type": "string"
                        }
                    }
                },
                "item_discount": {
                    "type": "object",
                    "properties": {
                        "coupon_id": {
                            "type": "integer"
                        },
                        "expire": {
                            "type": "integer"
                        },
                        "return_absolute": {
                            "type": "integer"
                        },
                        "return_percent": {
                            "type": "integer"
                        }
                    }
                },
                "item_size": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "integer"
                        },
                        "name": {
                            "type": "string"
                        }
                    }
                },
                "item_type": {
                    "type": "string"
                },
                "item_variants": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "id": {
                                "type": "string"
                            },
                            "name": {
                                "type": "string"
                            },
                            "quantity": {
                                "type": "integer"
                            },
                            "size": {
                                "type": "string"
                            }
                        }
                    }
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "name": {
                    "type": "string"
                },
                "num_comments": {
                    "type": "integer"
                },
                "num_likes": {
                    "type": "integer"
                },
                "photos": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "price": {
                    "type": "integer"
                },
                "seller": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "integer"
                        },
                        "name": {
                            "type": "string"
                        },
                        "num_sell_items": {
                            "type": "integer"
                        },
                        "ratings": {
                            "type": "object",
                            "properties": {
                                "bad": {
                                    "type": "integer"
                                },
                                "good": {
                                    "type": "integer"
                                },
                                "normal": {
                                    "type": "integer"
                                }
                            }
                        },
                        "shop_id": {
                            "type": "string"
                        }
                    }
                },
                "shipping_class": {
                    "type": "object",
                    "properties": {
                        "fee": {
                            "type": "integer"
                        },
                        "id": {
                            "type": "integer"
                        }
                    }
                },
                "shipping_duration": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "integer"
                        },
                        "max_days": {
                            "type": "integer"
                        },
                        "min_days": {
                            "type": "integer"
                        },
                        "name": {
                            "type": "string"
                        }
                    }
                },
                "shipping_from_area": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "integer"
                        },
                        "name": {
                            "type": "string"
                        }
                    }
                },
                "shipping_method": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "integer"
                        },
                        "name": {
                            "type": "string"
                        }
                    }
                },
                "shipping_payer": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "string"
                        },
                        "id": {
                            "type": "integer"
                        },
                        "name": {
                            "type": "string"
                        }
                    }
                },
                "shops_shipping_fee": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "updated": {
                    "type": "integer"
                }
            }
        },
        "mercari.GetItemCategoriesResp": {
            "type": "object",
            "properties": {
                "master_categories": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "id": {
                                "type": "string"
                            },
                            "level": {
                                "type": "string"
                            },
                            "name": {
                                "type": "string"
                            },
                            "parent_id": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "mercari.GetSimilarItemsResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mercari.SimilarItem"
                    }
                }
            }
        },
        "mercari.GetTodoListResp": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mercari.ToDo"
                    }
                },
                "next_page_token": {
                    "type": "string"
                }
            }
        },
        "mercari.GetTransactionByItemIDResponse": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "item_id": {
                    "type": "string"
                },
                "paid_price": {
                    "type": "integer"
                },
                "price": {
                    "type": "integer"
                },
                "seller_id": {
                    "type": "string"
                },
                "shipping_info": {
                    "type": "object",
                    "properties": {
                        "buyer_shipping_fee": {
                            "type": "string"
                        },
                        "shipping_method_name": {
                            "type": "string"
                        },
                        "status": {
                            "type": "string"
                        },
                        "tracking_number": {
                            "type": "string"
                        }
                    }
                },
                "status": {
                    "type": "string"
                },
                "updated_time": {
                    "type": "integer"
                }
            }
        },
        "mercari.GetUserByUserIDResponse": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "integer"
                },
                "has_identity_verified": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "introduction": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "num_ratings": {
                    "type": "integer"
                },
                "num_sell_items": {
                    "type": "integer"
                },
                "photo_thumbnail_url": {
                    "type": "string"
                },
                "photo_url": {
                    "type": "string"
                },
                "proper": {
                    "type": "boolean"
                },
                "ratings": {
                    "type": "object",
                    "properties": {
                        "bad": {
                            "type": "integer"
                        },
                        "good": {
                            "type": "integer"
                        }
                    }
                },
                "star_rating_score": {
                    "type": "integer"
                },
                "user_badges": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "Description": {
                                "type": "string"
                            },
                            "ID": {
                                "type": "integer"
                            },
                            "IconURL": {
                                "type": "string"
                            },
                            "Name": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "mercari.ItemDiscount": {
            "type": "object",
            "properties": {
                "return_percent": {
                    "type": "integer"
                }
            }
        },
        "mercari.PostTransactionReviewResponse": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "integer"
                },
                "failure_details": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "string"
                        },
                        "reasons": {
                            "type": "string"
                        }
                    }
                },
                "request_id": {
                    "type": "string"
                },
                "review_status": {
                    "type": "string"
                }
            }
        },
        "mercari.SearchItemsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_buyandship_supply-svr_biz_infrasturcture_mercari.Item"
                    }
                },
                "meta": {
                    "type": "object",
                    "properties": {
                        "has_next": {
                            "type": "boolean"
                        },
                        "num_found": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "mercari.SimilarItem": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "item_type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "photos": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "price": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "mercari.ToDo": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "integer"
                },
                "item_id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "photo_url": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "supply.Account": {
            "type": "object",
            "properties": {
                "active_at": {
                    "type": "string"
                },
                "address1": {
                    "type": "string"
                },
                "address2": {
                    "type": "string"
                },
                "banned_at": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "family_name": {
                    "type": "string"
                },
                "family_name_kana": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "first_name_kana": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "prefecture": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "telephone": {
                    "type": "string"
                },
                "zip_code1": {
                    "type": "string"
                },
                "zip_code2": {
                    "type": "string"
                }
            }
        },
        "supply.BidStatus": {
            "type": "object",
            "properties": {
                "has_bid": {
                    "type": "boolean",
                    "example": true
                },
                "is_winning": {
                    "type": "boolean",
                    "example": false
                },
                "my_highest_bid": {
                    "type": "integer",
                    "example": 950
                }
            }
        },
        "supply.MercariFetchItemsReq": {
            "type": "object",
            "properties": {
                "item_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "supply.MercariGetAccountResp": {
            "type": "object",
            "properties": {
                "accounts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/supply.Account"
                    }
                }
            }
        },
        "supply.MercariGetTokenResp": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "supply.MercariLoginCallBackReq": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "redirectUrl": {
                    "type": "string"
                },
                "scope": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "supply.MercariManualSwitchAccountReq": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "integer"
                }
            }
        },
        "supply.MercariPostMessageReq": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                },
                "trx_id": {
                    "type": "string"
                }
            }
        },
        "supply.MercariPostMessageResp": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "integer"
                },
                "body": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "trx_id": {
                    "type": "string"
                }
            }
        },
        "supply.MercariPostOrderReq": {
            "type": "object",
            "properties": {
                "checksum": {
                    "type": "string"
                },
                "delivery_id": {
                    "type": "string"
                },
                "item_id": {
                    "type": "string"
                },
                "ref_currency": {
                    "type": "string"
                },
                "ref_id": {
                    "type": "string"
                },
                "ref_price": {
                    "type": "integer"
                }
            }
        },
        "supply.MercariPostOrderResp": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "integer"
                },
                "buyer_shipping_fee": {
                    "type": "integer"
                },
                "checksum": {
                    "type": "string"
                },
                "coupon_id": {
                    "type": "integer"
                },
                "item_id": {
                    "type": "string"
                },
                "paid_price": {
                    "type": "integer"
                },
                "price": {
                    "type": "integer"
                },
                "trx_id": {
                    "type": "string"
                }
            }
        },
        "supply.MercariRegisterAccountReq": {
            "type": "object",
            "properties": {
                "active_at": {
                    "type": "string"
                },
                "address1": {
                    "type": "string"
                },
                "address2": {
                    "type": "string"
                },
                "banned_at": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "family_name": {
                    "type": "string"
                },
                "family_name_kana": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "first_name_kana": {
                    "type": "string"
                },
                "prefecture": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "telephone": {
                    "type": "string"
                },
                "zip_code1": {
                    "type": "string"
                },
                "zip_code2": {
                    "type": "string"
                }
            }
        },
        "supply.MercariRegisterAccountResp": {
            "type": "object",
            "properties": {
                "account": {
                    "$ref": "#/definitions/supply.Account"
                }
            }
        },
        "supply.Seller": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "seller123"
                },
                "rating": {
                    "type": "number",
                    "example": 98.5
                }
            }
        },
        "supply.YahooGetAuctionItemAuthResp": {
            "type": "object",
            "properties": {
                "auction_item": {
                    "$ref": "#/definitions/supply.YahooGetAuctionItemResp"
                },
                "bid_status": {
                    "$ref": "#/definitions/supply.BidStatus"
                },
                "is_watching": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "supply.YahooGetAuctionItemResp": {
            "type": "object",
            "properties": {
                "auction_id": {
                    "type": "string",
                    "example": "x12345"
                },
                "bids": {
                    "type": "integer",
                    "example": 5
                },
                "current_price": {
                    "type": "integer",
                    "example": 1000
                },
                "description": {
                    "type": "string",
                    "example": "Item description..."
                },
                "end_time": {
                    "type": "string",
                    "example": "2025-10-30T23:59:59Z"
                },
                "image": {
                    "type": "string",
                    "example": "https://example.com/image.jpg"
                },
                "item_status": {
                    "type": "string",
                    "example": "open"
                },
                "seller": {
                    "$ref": "#/definitions/supply.Seller"
                },
                "start_price": {
                    "type": "integer",
                    "example": 500
                },
                "start_time": {
                    "type": "string",
                    "example": "2025-10-22T00:00:00Z"
                },
                "title": {
                    "type": "string",
                    "example": "Sample Item Title"
                }
            }
        },
        "supply.YahooPlaceBidReq": {
            "type": "object",
            "properties": {
                "auction_id": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "transaction_type": {
                    "type": "string"
                },
                "ys_ref_id": {
                    "type": "string"
                }
            }
        },
        "supply.YahooPlaceBidResp": {
            "type": "object",
            "properties": {
                "auction_id": {
                    "type": "string",
                    "example": "x12345"
                },
                "bid_id": {
                    "type": "string",
                    "example": "bid_12345"
                },
                "bid_time": {
                    "type": "string",
                    "example": "2025-10-22T12:00:00Z"
                },
                "price": {
                    "type": "integer",
                    "example": 1000
                },
                "quantity": {
                    "type": "integer",
                    "example": 1
                },
                "status": {
                    "type": "string",
                    "example": "Success"
                },
                "total_price": {
                    "type": "integer",
                    "example": 1100
                }
            }
        },
        "supply.YahooTransaction": {
            "type": "object",
            "properties": {
                "auction_id": {
                    "type": "string",
                    "example": "x12345"
                },
                "current_price": {
                    "type": "integer",
                    "example": 1000
                },
                "req_price": {
                    "type": "integer",
                    "example": 1000
                },
                "status": {
                    "type": "string",
                    "example": "completed"
                },
                "transaction_id": {
                    "type": "string",
                    "example": "txn_abc123"
                },
                "transaction_type": {
                    "type": "string",
                    "example": "BID"
                },
                "ys_ref_id": {
                    "type": "string",
                    "example": "YS-REF-001"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
