// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	bns_supply "github.com/buyandship/supply-service/biz/router/bns/supply"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	bns_supply.Register(r)
}
